Internal time enhancement
razorpay/hypertrace-ingester pull request #119
Opened 2022-12-22 05:58 UTC by suddendust

2022-12-22 09:11 UTC, Harnoor-se7en commented
Need at least 1 week to review this

2022-12-22 11:02 UTC, suddendust commented
> Need at least 1 week to review this

Just need to review the tests cases + the enricher + the algo. Rest is just refactoring.

2022-12-27 14:10 UTC, Harnoor-se7en requested changes
1st Iteration. Also pls fix the failing CI checks.

2022-12-27 14:10 UTC, Harnoor-se7en commented on hypertrace-trace-enricher/enriched-span-constants/src/main/java/org/hypertrace/traceenricher/enrichedspan/constants/EnrichedSpanConstants.java
> +  public static final String API_INTERNAL_DURATION = "enriched.internal.duration.millis";
How about `API_NODE_INTERNAL_DURATION`?

2022-12-27 14:10 UTC, Harnoor-se7en commented on hypertrace-trace-enricher/hypertrace-trace-enricher-impl/src/main/java/org/hypertrace/traceenricher/enrichment/enrichers/ApiNodeInternalDurationEnricher.java
> +    return lookaheadEdge.getStartTimeMillis() >= endTimeMillis;
Instead of this condition, we should rely on `ChildOfRef` which is more accurate.

2022-12-27 14:10 UTC, Harnoor-se7en commented on hypertrace-trace-enricher/hypertrace-trace-enricher-impl/src/main/java/org/hypertrace/traceenricher/enrichment/enrichers/ApiNodeInternalDurationEnricher.java
> +    } catch (Exception e) {
Duplicate catch block. Pls remove it as the same log exists in EnrichmentProcessor.java

2022-12-27 14:10 UTC, Harnoor-se7en commented on hypertrace-trace-enricher/enriched-span-constants/src/main/java/org/hypertrace/traceenricher/enrichedspan/constants/utils/SpanUtils.java
> +    if (event.getMetrics() == null || event.getMetrics().getMetricMap().isEmpty()) {
if MetricMap is null will it throw NPE?

2022-12-27 14:10 UTC, Harnoor-se7en commented on hypertrace-trace-enricher/hypertrace-trace-enricher-impl/src/main/java/org/hypertrace/traceenricher/enrichment/enrichers/ApiNodeInternalDurationEnricher.java
> +                  SpanUtils.getMetricValue(entryEvent, "Duration", -1);
Constant for "Duration".

2022-12-27 14:10 UTC, Harnoor-se7en commented on hypertrace-trace-enricher/hypertrace-trace-enricher-impl/src/main/java/org/hypertrace/traceenricher/enrichment/enrichers/ApiNodeInternalDurationEnricher.java
> +              enrichSpan(entryEvent, entryApiBoundaryEventDuration, totalWaitTime);
enrichEvent

2022-12-27 14:10 UTC, Harnoor-se7en commented on hypertrace-trace-enricher/hypertrace-trace-enricher-impl/src/main/java/org/hypertrace/traceenricher/enrichment/enrichers/ApiNodeInternalDurationEnricher.java
> +    //    apiTraceGraph.getOutboundEdgesForApiNode(apiNode).stream()
nit: remove commented

2022-12-28 08:46 UTC, suddendust commented on hypertrace-trace-enricher/hypertrace-trace-enricher-impl/src/main/java/org/hypertrace/traceenricher/enrichment/enrichers/ApiNodeInternalDurationEnricher.java
> +    return lookaheadEdge.getStartTimeMillis() >= endTimeMillis;
CHILD_OF what? The parent span? All of these spans are child of parent span, as we filter FOLLOWS_FROM spans while creating the normalised edges.

2022-12-28 08:46 UTC, suddendust commented on hypertrace-trace-enricher/hypertrace-trace-enricher-impl/src/main/java/org/hypertrace/traceenricher/enrichment/enrichers/ApiNodeInternalDurationEnricher.java
> +    } catch (Exception e) {
Sure, done.

2022-12-28 08:49 UTC, suddendust commented on hypertrace-trace-enricher/enriched-span-constants/src/main/java/org/hypertrace/traceenricher/enrichedspan/constants/utils/SpanUtils.java
> +    if (event.getMetrics() == null || event.getMetrics().getMetricMap().isEmpty()) {
True but it's guaranteed to be non NULL, the way an `Event` is constructed in `JaegerSpanNormalizer`. From the same logic, I can also remove the check on `event.getMetrics` though, as this is also guaranteed to be non-null.

2022-12-28 08:50 UTC, suddendust commented on hypertrace-trace-enricher/hypertrace-trace-enricher-impl/src/main/java/org/hypertrace/traceenricher/enrichment/enrichers/ApiNodeInternalDurationEnricher.java
> +                  SpanUtils.getMetricValue(entryEvent, "Duration", -1);
Will extract this out to a `MetricConstants` class, it's used like this throughout the codebase.

2022-12-28 08:50 UTC, suddendust commented on hypertrace-trace-enricher/hypertrace-trace-enricher-impl/src/main/java/org/hypertrace/traceenricher/enrichment/enrichers/ApiNodeInternalDurationEnricher.java
> +              enrichSpan(entryEvent, entryApiBoundaryEventDuration, totalWaitTime);
done

2022-12-28 08:50 UTC, suddendust commented on hypertrace-trace-enricher/hypertrace-trace-enricher-impl/src/main/java/org/hypertrace/traceenricher/enrichment/enrichers/ApiNodeInternalDurationEnricher.java
> +    //    apiTraceGraph.getOutboundEdgesForApiNode(apiNode).stream()
This block has been removed.

2023-01-02 09:18 UTC, Harnoor-se7en commented on hypertrace-trace-enricher/hypertrace-trace-enricher-impl/src/main/java/org/hypertrace/traceenricher/enrichment/enrichers/ApiNodeInternalDurationEnricher.java
> +    return lookaheadEdge.getStartTimeMillis() >= endTimeMillis;
Understood, from instrumentation actually, there is no way to state the below relation concretely

- c2 depends on c1 where both c1 and c2 have CHILD_OF relation with the P1.

![Screenshot 2023-01-02 at 2 47 03 PM](https://user-images.githubusercontent.com/100941492/210212704-5886b255-3b72-406a-b3db-b9107ed6b54b.png)

2023-01-02 09:19 UTC, Harnoor-se7en commented on hypertrace-trace-enricher/hypertrace-trace-enricher-impl/src/main/java/org/hypertrace/traceenricher/enrichment/enrichers/ApiNodeInternalDurationEnricher.java
> +    return lookaheadEdge.getStartTimeMillis() >= endTimeMillis;
Hence this condition looks fine to me.

2023-01-02 09:21 UTC, Harnoor-se7en approved these changes
Haven't reviewed the test cases yet, but the business logic looks good to me. 
Approving

2023-01-04 18:00 UTC, merged